{{- $ := . }}
{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: proxy-ingress
  namespace: {{ .Release.Namespace }}
  annotations:
    nginx.ingress.kubernetes.io/ssl-passthrough: "true"
spec:
  ingressClassName: nginx
  tls:
    - secretName: https-certificates
      hosts:
{{- range list "" "*." "*.ws." }}
      - "{{ . }}{{ $.Values.ingress.domain }}"
{{- end }}
  rules:
{{- range list "" "*." "*.ws." }}
    - host: "{{ . }}{{ $.Values.ingress.domain }}"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: proxy
                port:
                  number: 443
{{- end }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: gitlab-ingress
  namespace: {{ .Release.Namespace }}
spec:
  ingressClassName: nginx
  tls:
    - secretName: gitlab-https-certificates
      hosts:
        - "gitlab.{{ $.Values.ingress.domain }}"
  rules:
    - host: "gitlab.{{ $.Values.ingress.domain }}"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: gitlab
                port:
                  number: 80
{{- end }}
