# All dependencies should be deployed to the control-plane. This allows
# connection of ad-hoc nodes without losing data if they stop

.affinity:  &affinity
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
      - matchExpressions:
        - key: node-role.kubernetes.io/control-plane
          operator: In
          values:
          - "true"

# Configuration for the ingress controllers
ingress:
  enabled: false
  domain: gitpod.io

# Configuration for Ingress-NGINX Helm package
ingressnginx:
  controller:
    config: {}
    extraArgs:
      enable-ssl-passthrough: true

minio:
  enabled: true
  affinity:
    <<: *affinity
  auth:
    rootUser: root
    rootPassword: password
  resources:
    requests:
      # defaults to 4GB, set to 2GB to be able to start on smaller instances
      memory: 2G
  extraEnvVars:
    - name: MINIO_SKIP_CLIENT
      value: "yes"
  persistence:
    # The data will be canned each restart (likely a new day)
    enabled: false

registry:
  enabled: false
  affinity:
    <<: *affinity
  persistence:
    enabled: true
    size: 100Gi
  tlsSecretName: builtin-registry-certs
